### ISSUE TITLE
Lang-data is not stored in the dist folder.

### ISSUE THREAD

**Issue by cokia** [junhoyeo/kakao-gift-ocr#4]
when I run 
`yarn`
`yarn build`
`yarn test`

it makes error 
`  1) getInfo function test
       should return giftCard information:
     Uncaught Error: Error: ENOENT: no such file or directory, open '/Users/h4nuko0n/kakao-gift-ocr/dist/data/lang-data/kor.traineddata.gz'
      at ChildProcess.<anonymous> (node_modules/tesseract.js/src/createWorker.js:141:15)
      at emit (internal/child_process.js:881:12)
      at processTicksAndRejections (internal/process/task_queues.js:85:21)
`

I think Issues where ./data is not copied to the under ./dist

**Comment by junhoyeo** [comment]
Resolved at #6
